name: Push to main on dai-release plugin

on: workflow_call

jobs:
  call-ci-workflow:
    name: Run build & test for dai-release plugin
    uses: ./.github/workflows/reusable-build.yaml
    with:
      plugin-path: ./plugins/dai-release
  version-tag:
    uses: ./.github/workflows/version.yaml
    needs: [ call-ci-workflow ]
    with:
      plugin-path: ./plugins/dai-release
      plugin: dai-release
  github-publish:
    needs: [ call-ci-workflow, version-tag]
    uses: ./.github/workflows/github-publish.yaml
    with:
      plugin-path: ./plugins/dai-release
  npm-publish:
    needs: [ call-ci-workflow, version-tag, github-publish ]
    uses: ./.github/workflows/npm-publish.yaml
    secrets: inherit
    with:
      plugin-path: ./plugins/dai-release
