name: Publish dai-release plugin

on: workflow_dispatch

jobs:
  call-ci-workflow:
    name: Run build & test for dai-release plugin
    uses: ./.github/workflows/reusable-build.yaml
    with:
      plugin-path: ./plugins/dai-release
      publish: true
