name: Push to main on dai-release-common plugin

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      # Ignore changes to READMEs and other Markdown.
      - 'plugins/dai-release-common/**/README*'
      - 'plugins/dai-release-common/**/*.md'
      - 'plugins/dai-release/**'  
      - 'plugins/dai-release-backend/**' 

jobs:
  call-ci-workflow:
    name: Run build & test for dai-release-common plugin
    uses: ./.github/workflows/reusable-build.yaml
    with:
      plugin-path: ./plugins/dai-release-common