name: Publish dai-release-common plugin

on:
  workflow_dispatch:
    inputs:
      github-publish:
        description: 'Github publish'
        required: true
        default: false
        type: boolean
      npm-publish:
        description: 'Npm publish'
        required: true
        default: false
        type: boolean

jobs:
  github-publish:
    if: ${{ inputs.github-publish == true }}
    uses: ./.github/workflows/github-publish.yaml
    with:
      plugin-path: ./plugins/dai-release-common
  npm-publish:
    if: ${{ inputs.npm-publish == true }}
    uses: ./.github/workflows/npm-publish.yaml
    secrets: inherit
    with:
      plugin-path: ./plugins/dai-release-common

