name: Publish dai-release-backend plugin

on: workflow_dispatch

jobs:
  call-ci-workflow:
    name: Run build & test for dai-release-backend plugin
    uses: ./.github/workflows/reusable-build.yaml
    with:
      plugin-path: ./plugins/dai-release-backend
      publish: true
