name: Push to main on dai-release plugin

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      # Ignore changes to READMEs and other Markdown.
      - 'plugins/dai-release/**/README*'
      - 'plugins/dai-release/**/*.md'
      - 'plugins/dai-release-backend/**'  
      - 'plugins/dai-release-common/**'  

jobs:
  call-ci-workflow:
    name: Run build & test for dai-release plugin
    uses: ./.github/workflows/reusable-build.yaml
    with:
      plugin-path: ./plugins/dai-release