name: Build & test npm module

on:
  workflow_call:
    inputs:
      plugin-path:
        required: true
        type: string

jobs:
  build_job:
    name: Build & Test
    runs-on: ubuntu-latest
    env:
      NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.ref_name }} # need to map it to main branch
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://npm.pkg.github.com'
      - name: Install dot-icon from npm registry - Configure npm to use npm registry for @digital-ai scope
        if: ${{ inputs.plugin-path == './plugins/dai-release' }}
        run: |
          npm config set @digital-ai:registry https://registry.npmjs.org/
      - name: Install dot-icon from npm registry.
        if: ${{ inputs.plugin-path == './plugins/dai-release' }}
        working-directory: ${{ inputs.plugin-path }}
        run: |
          yarn add @digital-ai/dot-icons --registry=https://registry.npmjs.org/
      - name: Install dot-icon from npm registry - Reset npm config.
        if: ${{ inputs.plugin-path == './plugins/dai-release' }}
        run: |
          npm config delete @digital-ai:registry
      - name: Install dependencies
        working-directory: ${{ inputs.plugin-path }}
        run: yarn install
      - name: Run tsc
        working-directory: ${{ inputs.plugin-path }}
        run: yarn tsc
      - name: Build
        working-directory: ${{ inputs.plugin-path }}
        run: yarn build
      - name: Run tests
        working-directory: ${{ inputs.plugin-path }}
        run: yarn test
