name: Update-Dependency of dai-release-common plugin

on: workflow_call

jobs:
  update-dependency:
    name: Update Latest version of dai-release-common.
    runs-on: ubuntu-latest
    env:
      NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.ref_name }}
      - name: Update Package of Other Module
        run: |
          # Extract the version of the package from the output of the previous jobs
          PACKAGE_VERSION=$(grep '"version"' ./plugins/dai-release-common/package.json | awk -F '"' '{print $4}')
          echo $PACKAGE_VERSION
          echo "Updating package.json: ./plugins/dai-release/package.json"
          sed -i 's/"@digital-ai\/plugin-dai-release-common": ".*"/"@digital-ai\/plugin-dai-release-common": "'"$PACKAGE_VERSION"'"/' ./plugins/dai-release/package.json
          echo "Updating package.json: ./plugins/dai-release-backend/package.json"
          sed -i 's/"@digital-ai\/plugin-dai-release-common": ".*"/"@digital-ai\/plugin-dai-release-common": "'"$PACKAGE_VERSION"'"/' ./plugins/dai-release-backend/package.json
          echo "Done"
      - name: Commit and Push Changes
        run: |
          git pull origin ${{ github.ref_name }}
          git config user.name "GitHub Actions"
          git config user.email "<>"
          git add .
          git commit -m "chore: update dependencies"
          git push origin ${{ github.ref_name }}
